Failure # 1 (occurred at 2023-06-02_15-02-17)
[36mray::ImplicitFunc.train()[39m (pid=13227, ip=172.17.0.3, repr=train)
  File "/home/vscode/.cache/pypoetry/virtualenvs/deep-learning-G3c9zDRR-py3.9/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 384, in train
    raise skipped from exception_cause(skipped)
  File "/home/vscode/.cache/pypoetry/virtualenvs/deep-learning-G3c9zDRR-py3.9/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 336, in entrypoint
    return self._trainable_func(
  File "/home/vscode/.cache/pypoetry/virtualenvs/deep-learning-G3c9zDRR-py3.9/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 653, in _trainable_func
    output = fn()
  File "/workspaces/MLopdracht/hypertune.py", line 29, in train
    trainloader, validloader = ArabicTrain.txt, ArabicTest.txt
NameError: name 'ArabicTrain' is not defined
